[package]
name = "ty-fbx"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "Command-line tools for Voxel Max (https://voxelmax.com)."

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
