[package]
name = "ty-math"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Math types and utilities shared across all tyt crates."
