[package]
name = "ty-math-serde"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Serde-compatible parity types for ty-math."

[dependencies]
serde = { version = "1", features = ["derive"] }
ty-math = { version = "0.1.0" }
